### ISSUE TITLE
Improvement in chat UI

### ISSUE THREAD

**Issue by kshitijalwadhi** [devclub-iitd/ShareACab#153]
Show time of message sent in chat screen corresponding to every message.

**Comment by rish07** [comment]
Hey @kshitijalwadhi, I would like to work on this issue.

**Comment by kshitijalwadhi** [comment]
Hi @rish07.
You are very welcome to contribute to this repository.
Please follow the [contribution guidlines](https://github.com/devclub-iitd/ShareACab/blob/master/CONTRIBUTING.md) before submitting your pull request.

**Comment by rish07** [comment]
Sure, do you have UI ready as to how the time stamp should look in the message bubble?

**Comment by kshitijalwadhi** [comment]
We didn't make a prototype for this. You can judge on your own, how it will look better.
Maybe we can have it like a standard chat window where the time is showed at the bottom right of the message bubble. 
I have attached a screenshot of the presently implemented chat window.
After you are done with this, if you want to experiment, maybe you can also try showing a date above a chat bubble when a message is sent at a new date from the previous message. (similar to how it works in whatsapp).

<img width="216" alt="Screenshot_20201206-140212_Share_a_Cab" src="https://user-images.githubusercontent.com/52427677/101929412-d0741d00-3bfc-11eb-8a2f-cd6f4e68deff.png">
