### ISSUE TITLE
Container in trip Card is of fixed size

### ISSUE THREAD

**Issue by Deepanshu-Rohilla** [devclub-iitd/ShareACab#71]
It would create problems if we have different number of people in the group.

**Comment by Ishaan21** [comment]
I think we are not showing members list on card. They will be shown onTap

**Comment by Deepanshu-Rohilla** [comment]
Whatever be the case, fixing the size is not a good practice. Making the size dynamic would make the app maintainable. Moreover if in future we have to add or remove something, we would not have to adjust the size again and again

**Comment by Deepanshu-Rohilla** [comment]
I'll work on this
