### ISSUE TITLE
Adding tooltips to buttons

### ISSUE THREAD

**Issue by tmibvishal** [devclub-iitd/ShareACab#81]
**Description**
Adding tooltips to  floating action button and icon buttons in action bar

**Additional context**
Most of the icons like floating action button and icons in action bar of different screen have no tooltip. Tooltip will help guess the functionality of button (which is not possible just by looking at the icon). When you hold the icon a little tooltip with name of button pops up (if added).

**Comment by kshitijalwadhi** [comment]
I'll add them
