### ISSUE TITLE
Theme color does not apply to current page icon while switching between themes

### ISSUE THREAD

**Issue by Deepanshu-Rohilla** [devclub-iitd/ShareACab#91]
After changing the colour theme, the Home Icon in curved navigation bar does not respond to the theme change.
However it adapts the new theme if we change the screens (from curved navigation bar only)
![WhatsApp Video 2020-06-11 at 10 54 52 PM](https://user-images.githubusercontent.com/52520071/84420009-0bd66480-ac37-11ea-971e-3a207e32cd46.gif)

**Comment by kshitijalwadhi** [comment]
This is not specific to the home screen but any screen from which we change the setting

**Comment by tmibvishal** [comment]
ye solve ho gya na @kshitijalwadhi ?

**Comment by kshitijalwadhi** [comment]
No sir, its there on one device am testing and absent on the other

**Comment by kshitijalwadhi** [comment]
Fixed by changes in upstream of library/flutter.
